### ISSUE TITLE
Paired doublequotes denoting empty string treated as unclosed string by vscode-netdata

### ISSUE THREAD

**Issue by jwoehr** [jaroborovsky/vscode-netdata#1]
The image shows the problem.
The paired doublequote null string 6th argument to `@dtw_tb_select()` leave vscode-netdata in unclosed string mode.

![image](https://github.com/jaroborovsky/vscode-netdata/assets/4604036/04f67309-69e7-413c-ac15-7c8dc3d0ddca)

BTW thank you for a very useful extension! There still is some NET.DATA out there 👍🏾

**Comment by jaroborovsky** [comment]
Hi, I've changed language definition. Please, try patched version 1.0.7.
